name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 8:30 PM UTC (12:00 AM IRST)
    - cron: "30 20 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: "█▓▒░"
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
